// -*- mode: c++ -*-
// 
// File pca.C generated by TPrincipal::MakeCode
// on Thu Mar 10 01:22:56 2016
// ROOT version 5.34/34
//
// This file contains the functions 
//
//    void  X2P(Double_t *x, Double_t *p); 
//    void  P2X(Double_t *p, Double_t *x, Int_t nTest);
//
// The first for transforming original data x in 
// pattern space, to principal components p in 
// feature space. The second function is for the
// inverse transformation, but using only nTest
// of the principal components in the expansion
// 
// See TPrincipal class documentation for more information 
// 
#ifndef __CINT__
#include <Rtypes.h> // needed for Double_t etc
#endif

//
// Static data variables
//
static Int_t    gNVariables = 10;

// Assignment of eigenvector matrix.
// Elements are stored row-wise, that is
//    M[i][j] = e[i * nVariables + j] 
// where i and j are zero-based
static Double_t gEigenVectors[] = {
  0.316228,
  0.105409,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  0.916667,
  -0.0833333,
  0.316228,
  0.105409,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  0.916667,
  0.316228,
  0.105409,
  0.916667,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  0.316228,
  0.105409,
  -0.0833333,
  0.916667,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  0.316228,
  0.105409,
  -0.0833333,
  -0.0833333,
  0.916667,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  0.316228,
  0.105409,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  0.916667,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  0.316228,
  0.105409,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  0.916667,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  0.316228,
  0.105409,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  -0.0833333,
  0.916667,
  -0.0833333,
  -0.0833333,
  0.316228,
  0.105409,
  -0.333333,
  -0.333333,
  -0.333333,
  -0.333333,
  -0.333333,
  -0.333333,
  -0.333333,
  -0.333333,
  0.316228,
  -0.948683,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0};

// Assignment to eigen value vector. Zero-based.
static Double_t gEigenValues[] = {
  1,
  1.11022e-16,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
};

// Assignment to mean value vector. Zero-based.
static Double_t gMeanValues[] = {
  0.9144,
  0.9144,
  0.9144,
  0.9144,
  0.9144,
  0.9144,
  0.9144,
  0.9144,
  0.9144,
  0.9144
};

// Assignment to sigma value vector. Zero-based.
static Double_t gSigmaValues[] = {
  2.5454,
  2.5454,
  2.5454,
  2.5454,
  2.5454,
  2.5454,
  2.5454,
  2.5454,
  2.5454,
  2.5454
};

// 
// The function   void X2P(Double_t *x, Double_t *p)
// 
void X2P(Double_t *x, Double_t *p) {
  for (Int_t i = 0; i < gNVariables; i++) {
    p[i] = 0;
    for (Int_t j = 0; j < gNVariables; j++)
      p[i] += (x[j] - gMeanValues[j]) 
        * gEigenVectors[j *  gNVariables + i] / gSigmaValues[j];

  }
}

// 
// The function   void P2X(Double_t *p, Double_t *x, Int_t nTest)
// 
void P2X(Double_t *p, Double_t *x, Int_t nTest) {
  for (Int_t i = 0; i < gNVariables; i++) {
    x[i] = gMeanValues[i];
    for (Int_t j = 0; j < nTest; j++)
      x[i] += p[j] * gSigmaValues[i] 
        * gEigenVectors[i *  gNVariables + j];
  }
}

// EOF for pca.C
