// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/04       [336388]
Creator        : dsg12
Date           : Tue Jan 26 14:58:08 2016
Host           : Linux hepadmin.hep.ph.ic.ac.uk 2.6.32-279.14.1.el6.x86_64 #1 SMP Tue Nov 6 23:43:09 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/hep/dsg12/mproject/ICMSciThesisHiggsInv
Training events: 5661
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "10" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "30" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "6" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 37
dijet_deta                    dijet_deta                    dijet_deta                    Dijet #Delta#eta                                                'F'    [4.20014095306,7.98615837097]
forward_tag_eta               forward_tag_eta               forward_tag_eta               Forward Tag #eta                                                'F'    [-4.69821596146,4.67679548264]
metnomu_significance          metnomu_significance          metnomu_significance          MET Significance (No Muons)                                     'F'    [3.50013852119,82.6521072388]
sqrt_ht                       sqrt_ht                       sqrt_ht                       Square Root HCAL Scalar Sum of EnergyGeV^{0.5}                         'F'    [8.17473888397,26.6764717102]
alljetsmetnomu_mindphi        alljetsmetnomu_mindphi        alljetsmetnomu_mindphi        All Jets - MET Min. #Delta#phi (No Muons)                                  'F'    [2.00026941299,2.99989032745]
dijet_M                       dijet_M                       dijet_M                       Dijet Mass                    GeV                               'F'    [258.105651855,4278.94238281]
metnomuons                    metnomuons                    metnomuons                    MET (No Muons)                GeV                               'F'    [23.2741107941,668.498352051]
jet1_E                        jet1_E                        jet1_E                        Jet1E                         GeV                               'F'    [50.1926002502,3543.35351562]
jet2_E                        jet2_E                        jet2_E                        Jet2E                         GeV                               'F'    [45.1579933167,3254.35913086]
jet1_pt                       jet1_pt                       jet1_pt                       jet1_pt                                                         'F'    [31.5231437683,529.926513672]
jet2_pt                       jet2_pt                       jet2_pt                       jet2_pt                                                         'F'    [30.0040664673,231.104232788]
jet1_eta                      jet1_eta                      jet1_eta                      jet1_eta                                                        'F'    [-4.50705051422,4.61924409866]
jet2_eta                      jet2_eta                      jet2_eta                      jet2_eta                                                        'F'    [-4.69821596146,4.67679548264]
jet1_phi                      jet1_phi                      jet1_phi                      jet1_phi                                                        'F'    [-3.14112663269,3.14023947716]
jet2_phi                      jet2_phi                      jet2_phi                      jet2_phi                                                        'F'    [-3.14123821259,3.14072704315]
jet_csv1                      jet_csv1                      jet_csv1                      jet_csv1                                                        'F'    [-1,0.999998807907]
jet_csv2                      jet_csv2                      jet_csv2                      jet_csv2                                                        'F'    [-1,0.850831270218]
dijet_dphi                    dijet_dphi                    dijet_dphi                    dijet_dphi                                                      'F'    [1.71661376953e-05,2.1988363266]
metnomu_x                     metnomu_x                     metnomu_x                     metnomu_x                                                       'F'    [-503.073516846,442.795684814]
metnomu_y                     metnomu_y                     metnomu_y                     metnomu_y                                                       'F'    [-475.533874512,503.169708252]
sumet                         sumet                         sumet                         sumet                                                           'F'    [125.9584198,2819.18066406]
mht                           mht                           mht                           mht                                                             'F'    [43.9786148071,3542.43652344]
unclustered_et                unclustered_et                unclustered_et                unclustered_et                                                  'F'    [1.88566935062,3236.4375]
jetmet_mindphi                jetmet_mindphi                jetmet_mindphi                jetmet_mindphi                                                  'F'    [8.30441422295e-05,3.11834621429]
jetunclet_mindphi             jetunclet_mindphi             jetunclet_mindphi             jetunclet_mindphi                                               'F'    [3.51987982867e-05,3.05589818954]
metnomuunclet_dphi            metnomuunclet_dphi            metnomuunclet_dphi            metnomuunclet_dphi                                              'F'    [0.000921122322325,3.14155292511]
dijetmetnomu_vectorialSum_pt  dijetmetnomu_vectorialSum_pt  dijetmetnomu_vectorialSum_pt  dijetmetnomu_vectorialSum_pt                                    'F'    [0.15927632153,208.457580566]
dijetmetnomu_ptfraction       dijetmetnomu_ptfraction       dijetmetnomu_ptfraction       dijetmetnomu_ptfraction                                         'F'    [0.211141824722,0.78661185503]
jet1metnomu_scalarprod        jet1metnomu_scalarprod        jet1metnomu_scalarprod        jet1metnomu_scalarprod                                          'F'    [-47826.6367188,-17.9804859161]
jet2metnomu_scalarprod        jet2metnomu_scalarprod        jet2metnomu_scalarprod        jet2metnomu_scalarprod                                          'F'    [-38948.4570312,-12.9739093781]
n_jets_cjv_30                 n_jets_cjv_30                 n_jets_cjv_30                 n_jets_cjv_30                                                   'F'    [0,3]
n_jets_cjv_20EB_30EE          n_jets_cjv_20EB_30EE          n_jets_cjv_20EB_30EE          n_jets_cjv_20EB_30EE                                            'F'    [0,5]
n_jets_15                     n_jets_15                     n_jets_15                     n_jets_15                                                       'F'    [2,12]
n_jets_30                     n_jets_30                     n_jets_30                     n_jets_30                                                       'F'    [2,5]
cjvjetpt                      cjvjetpt                      cjvjetpt                      cjvjetpt                                                        'F'    [-1,122.264945984]
l1met                         l1met                         l1met                         l1met                                                           'F'    [9.99999997475e-07,2047.5]
n_vertices                    n_vertices                    n_vertices                    n_vertices                                                      'F'    [1,42]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 37 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dijet_deta", "forward_tag_eta", "metnomu_significance", "sqrt_ht", "alljetsmetnomu_mindphi", "dijet_M", "metnomuons", "jet1_E", "jet2_E", "jet1_pt", "jet2_pt", "jet1_eta", "jet2_eta", "jet1_phi", "jet2_phi", "jet_csv1", "jet_csv2", "dijet_dphi", "metnomu_x", "metnomu_y", "sumet", "mht", "unclustered_et", "jetmet_mindphi", "jetunclet_mindphi", "metnomuunclet_dphi", "dijetmetnomu_vectorialSum_pt", "dijetmetnomu_ptfraction", "jet1metnomu_scalarprod", "jet2metnomu_scalarprod", "n_jets_cjv_30", "n_jets_cjv_20EB_30EE", "n_jets_15", "n_jets_30", "cjvjetpt", "l1met", "n_vertices" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;
      fVmin[32] = 0;
      fVmax[32] = 0;
      fVmin[33] = 0;
      fVmax[33] = 0;
      fVmin[34] = 0;
      fVmax[34] = 0;
      fVmin[35] = 0;
      fVmax[35] = 0;
      fVmin[36] = 0;
      fVmax[36] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[37];
   double fVmax[37];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[37];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1.29845217305853);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 20.4799, 1, 1, 0.9207,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.912026,-99) , 
NN(
0, 
0, 
-1, 0.500725, 0, -1, 0.0243396,-99) , 
22, 107.182, 1, 0, 0.0801164,-99) , 
25, 2.73622, 1, 0, 0.489388,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.847187);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0967742, 1, 1, 0.872165,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.745635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444339,-99) , 
26, 26.2255, 1, 0, 0.600328,-99) , 
2, 4.52462, 0, 0, 0.7959,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.803777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325798,-99) , 
21, 286.876, 0, 0, 0.595696,-99) , 
NN(
0, 
0, 
-1, 17.2553, 1, -1, 0.0729026,-99) , 
22, 163.514, 1, 0, 0.19332,-99) , 
25, 2.33132, 1, 0, 0.471471,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.669973);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 20.4799, 1, 1, 0.702072,-99) , 
NN(
0, 
0, 
-1, 0.491117, 0, -1, 0.0322934,-99) , 
29, -122.561, 0, 0, 0.605771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
28, -532.73, 0, 0, 0.483162,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.503366);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.991759,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0884759,-99) , 
28, -157.594, 0, 0, 0.543752,-99) , 
9, 167.006, 0, 0, 0.614466,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.80908,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316745,-99) , 
5, 951.98, 0, 0, 0.632385,-99) , 
NN(
0, 
0, 
-1, 108.782, 1, -1, 0.0839753,-99) , 
26, 18.6984, 1, 0, 0.223787,-99) , 
24, 0.482082, 0, 0, 0.411876,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.456902);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 15.1612, 0, 1, 0.949983,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.729071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309538,-99) , 
5, 1319.1, 0, 0, 0.402211,-99) , 
2, 6.86656, 0, 0, 0.461417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
28, -532.73, 0, 0, 0.392666,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.495054);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330924,-99) , 
34, 20.4799, 1, 0, 0.549513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
29, -150.38, 0, 0, 0.50623,-99) , 
NN(
0, 
0, 
-1, 2.0495, 0, -1, 0.103206,-99) , 
23, 2.11755, 0, 0, 0.411233,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.330303);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.764578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494967,-99) , 
17, 0.894735, 0, 0, 0.591735,-99) , 
NN(
0, 
0, 
-1, 0.469238, 0, -1, 0.038583,-99) , 
28, -354.814, 0, 0, 0.499037,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.910541,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.193636,-99) , 
1, 2.81996, 0, 0, 0.380792,-99) , 
NN(
0, 
0, 
-1, 0.512997, 0, -1, 0.0535902,-99) , 
4, 2.12865, 1, 0, 0.182586,-99) , 
23, 2.18727, 0, 0, 0.396053,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.325543);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.785071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438694,-99) , 
34, 23.5535, 1, 0, 0.703684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0737109,-99) , 
29, -132.921, 0, 0, 0.633186,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.80668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306249,-99) , 
32, 2.22581, 1, 0, 0.364262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
23, 1.92408, 0, 0, 0.306286,-99) , 
23, 2.4835, 0, 0, 0.430047,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.22808);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 390.193, 0, 1, 0.850665,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.916945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409615,-99) , 
5, 1881.36, 0, 0, 0.439146,-99) , 
23, 2.84704, 0, 0, 0.487142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
23, 1.91592, 0, 0, 0.433345,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.241302);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1319.65, 0, 1, 0.587574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
29, -170.474, 0, 0, 0.559311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
23, 1.91128, 0, 0, 0.522364,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
